preload = ~/.themes/wallpapers/landscapes/evening-sky.png
wallpaper = eDP-1,~/.themes/wallpapers/landscapes/evening-sky.png
wallpaper = DP-2,~/.themes/wallpapers/landscapes/evening-sky.png
wallpaper = DP-3,~/.themes/wallpapers/landscapes/evening-sky.png
wallpaper = DP-4,~/.themes/wallpapers/landscapes/evening-sky.png
wallpaper = DP-5,~/.themes/wallpapers/landscapes/evening-sky.png
wallpaper = DP-6,~/.themes/wallpapers/landscapes/evening-sky.png
wallpaper = DP-7,~/.themes/wallpapers/landscapes/evening-sky.png
splash = false

