preload = ~/.themes/wallpapers/minimalistic/darker_unicat.png
wallpaper = eDP-1,~/.themes/wallpapers/minimalistic/darker_unicat.png
wallpaper = DP-1,~/.themes/wallpapers/minimalistic/darker_unicat.png
wallpaper = DP-2,~/.themes/wallpapers/minimalistic/darker_unicat.png
wallpaper = DP-3,~/.themes/wallpapers/minimalistic/darker_unicat.png
wallpaper = DP-4,~/.themes/wallpapers/minimalistic/darker_unicat.png
wallpaper = DP-5,~/.themes/wallpapers/minimalistic/darker_unicat.png
wallpaper = DP-6,~/.themes/wallpapers/minimalistic/darker_unicat.png
wallpaper = DP-7,~/.themes/wallpapers/landscapes/darker_unicat.png
splash = false

