preload = ~/.themes/space1.png
preload = ~/.themes/space2.png
preload = ~/.themes/outer_space.png

wallpaper = eDP-1,~/.themes/outer_space.png
wallpaper = DP-2,~/.themes/space1.png
wallpaper = DP-4,~/.themes/space1.png
wallpaper = DP-6,~/.themes/space1.png
wallpaper = DP-3,~/.themes/space2.png
wallpaper = DP-5,~/.themes/space2.png
wallpaper = DP-7,~/.themes/space2.png

splash = false

