console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  blue = '#88c0d0'
  green = '#a3be8c'
  orange = '#d08770'
  purple = '#b48ead'
  red = '#bf616a'
  teal = '#8fbcbb'
  yellow = '#ebcb8b'

[transient_prompt]
  template = ''
  foreground = ''
  background = 'transparent'
  foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}', '{{ if eq .Code 0 }}p:teal{{ end }}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .Path }} '
    foreground = 'p:blue'
    background = 'transparent'
    type = 'path'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if gt .Behind 0 }}{{ end }}{{ if gt .Ahead 0 }}{{ end }}'
    foreground = ''
    background = 'transparent'
    type = 'git'

    [blocks.segments.properties]
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = ''
    foreground = ''
    background = 'transparent'
    type = 'text'
    foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}', '{{ if eq .Code 0 }}p:teal{{ end }}']
