# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#3B4252

# Main text color
theme[main_fg]=#ECEFF4

# Title color for boxes
theme[title]=#ECEFF4

# Highlight color for keyboard shortcuts
theme[hi_fg]=#88C0D0

# Background color of selected item in processes box
theme[selected_bg]=#434C5E

# Foreground color of selected item in processes box
theme[selected_fg]=#88C0D0

# Color of inactive/disabled text
theme[inactive_fg]=#616E88

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#5E81AC

# Background color of the percentage meters
theme[meter_bg]=#616E88

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#5E81AC

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#B48EAD
theme[mem_box]=#A3BE8C
theme[net_box]=#BF616A
theme[proc_box]=#5E81AC

# Box divider line and small boxes line color
theme[div_line]=#4C566A

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#A3BE8C
theme[temp_mid]=#EBCB8B
theme[temp_end]=#BF616A

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#8FBCBB
theme[cpu_mid]=#81A1C1
theme[cpu_end]=#5E81AC

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#B48EAD
theme[free_mid]=#5E81AC
theme[free_end]=#5E81AC

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#81A1C1
theme[cached_mid]=#5E81AC
theme[cached_end]=#5E81AC

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#D08770
theme[available_mid]=#BF616A
theme[available_end]=#BF616A

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#A3BE8C
theme[used_mid]=#8FBCBB
theme[used_end]=#88C0D0

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#D08770
theme[download_mid]=#BF616A
theme[download_end]=#BF616A

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#A3BE8C
theme[upload_mid]=#8FBCBB
theme[upload_end]=#88C0D0

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#81A1C1
theme[process_mid]=#5E81AC
theme[process_end]=#B48EAD
