#"cursor.style" = "Block"
#"debug.render_timer" = false
live_config_reload = true
#theme = "Catppuccin"
[debug]
render_timer = false

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xF8BD96"
index = 16

[[colors.indexed_colors]]
color = "0xF5E0DC"
index = 17

[colors.bright]
black = "0x988BA2"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.cursor]
cursor = "0xF5E0DC"
text = "0x1E1D2F"

[colors.normal]
black = "0x6E6C7E"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.primary]
background = "0x1E1D2F"
foreground = "0xD9E0EE"

[env]
TERM = "xterm-256color"

[font]
size = 14
bold = {family="Hack Nerd Font",style="Bold"}
italic = {family="Hack Nerd Font",style="Italic"}
normal = {family="Hack Nerd Font",style="Regular"}
#offset = {x=0,y=0}
glyph_offset = {x=0,y=0}

[mouse]
#faux_scrolling_lines = 1
hide_when_typing = true
bindings = [ {mouse = "Middle", action = "Paste"}]

#[keyboard]
#bindings = [{key="N", mods="Control", action="CreateNewWindow"}]

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[shell]
#program = "/bin/zsh"
program = "/bin/zsh"
args = ["-l","-c","tmux attach || tmux"]

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Maximized"
opacity = 1.0
blur = true
dimensions = {columns=320,lines=160}
padding = { x=4, y=4}
